[tool.semantic_release]
branch = "main"
upload_to_pypi = false
upload_to_release = true
version_variables = [
    "routeros_backup/__about__.py:__version__:nf"
]

[tool.semantic_release.changelog]
exclude_commit_patterns = [
  "chore(?:\\([^)]*?\\))?: .+",
  "ci(?:\\([^)]*?\\))?: .+",
  "refactor(?:\\([^)]*?\\))?: .+",
  "style(?:\\([^)]*?\\))?: .+",
  "docs(?:\\([^)]*?\\))?: .+",
  "test(?:\\([^)]*?\\))?: .+",
  "build\\((?!deps\\): .+)",
  "Initial [Cc]ommit.*"
]