name: Build & Publish Docker Image

env:
  DOCKERHUB_TAG: "schwitzd/routeros-backup"

on:
  workflow_dispatch:

jobs:
  build:
    name: Build & Capture Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semantic_release.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install python-semantic-release

      - name: Run semantic-release
        id: semantic_release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release version  --no-changelog

  release:
    name: Release Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: VERSION=${{ needs.build.outputs.version }}
          tags: |
            ${{ env.DOCKERHUB_TAG }}:latest
            ${{ env.DOCKERHUB_TAG }}:${{ needs.build.outputs.version }}
          platforms: linux/amd64,linux/arm64

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ env.DOCKERHUB_TAG }}
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./README.md
          enable-url-completion: true
